import About from '~/components/About';
import { Link } from '@remix-run/react';

export default function Index() {
  return (
    <article className="flex flex-col justify-center mx-4 md:w-[80ch] gap-y-4 ">
      <div className="flex flex-col items-end gap-x-4">
        <h1 className="flex-none text-5xl leading-tight md:leading-tight  md:text-8xl text-gradient-theme">
          Welcome to StartupMate
        </h1>
        <p className="flex-none text-lg">
          - Your Partner in Entrepreneurship! 😉
        </p>
      </div>
      <p className="text-xl text-justify">
        Are you looking for a powerful tool to help you turn your business ideas
        into reality? Look no further! Our app, StartupMate, is designed to help
        you generate innovative business ideas, craft a winning business model,
        and bring your vision to life. With StartupMate, you'll have all the
        resources you need to take your first steps towards entrepreneurship
        success. Join the countless entrepreneurs who have already used
        StartupMate to launch their businesses and start your journey today!
      </p>
      <p className="border-l-8 border-accent pl-2">
        "And no, you didn't imagine it - this text was indeed generated by an
        AI! We promise StartupMate is much more creative than we are."
      </p>

      <div className="collapse collapse-arrow border border-base-300  bg-base-300 rounded-box ">
        <input type="checkbox" />
        <div className="collapse-title text-xl font-mediu">
          Read more about how it works
        </div>
        <div className="collapse-content">
          <About />
        </div>
      </div>

      <Link to="create" className="btn btn-lg btn-block btn-accent mt-3">
        GET STARTED!
      </Link>
    </article>
  );
}
